### ISSUE TITLE
Create Project Page

### ISSUE THREAD

**Issue by ashmitjsg** [Team-Abraxas/Abraxas-Website-2024#1]
Update the project page to showcase each year's project. It should have:

- A way to navigate to a specific year.
- Show the project of the year selected.
- The card should have a project title, details, and optional links.
- On clicking the project card, a modal should open with an in-detail explanation of the project (Project Abstract, Detail, Images, Advantage, Creator Name, Optional Refrences and links). 

# Review
@devilkiller-ag @TeamAbraxas

**Comment by shabdpatel** [comment]
Can I work in it?

**Comment by ashmitjsg** [comment]
Yup

**Comment by shabdpatel** [comment]
[](https://croing.com/#/ ) (**Services Section**)
[](https://jaisarita.vercel.app/#experience) (**Experience section**)

**Comment by shabdpatel** [comment]
[Croing services section](https://croing.com/#/)
[Experience section card templates](https://jaisarita.vercel.app/#experience)

**Comment by ashmitjsg** [comment]
Good Work! Keep Searching 💪🏼

**Comment by shabdpatel** [comment]
[Stories section](https://refire.heycusp.com/)
[Changing the accounting industry section](https://www.uplinq.com/)

**Comment by shabdpatel** [comment]
Created section for Project description and 3d model, Have to work more on positioning.

**Comment by shabdpatel** [comment]
Created a dropdown menu for selecting project years.
![Screenshot from 2024-03-13 23-11-04](https://github.com/Team-Abraxas/Abraxas-Website-2024/assets/122690804/64f7acbe-a4c7-411d-81da-ed5c7b6ae092)

**Comment by shabdpatel** [comment]
Created a basic carousel horizontal scroll using framer motion

**Comment by shabdpatel** [comment]
After creating a carousel for horizontal scrolling, there was an issue with setting the width limit of the scroll, which was later resolved.
![Screenshot from 2024-03-19 10-26-11](https://github.com/Team-Abraxas/Abraxas-Website-2024/assets/122690804/b753a878-a9b4-4c88-ad27-63f1ffe45333)

**Comment by ashmitjsg** [comment]
Make Card Backgrounds blurry, and remove borders. Why the models are not rendering?

**Comment by shabdpatel** [comment]
Added year navigation for the projects
![Screenshot from 2024-04-05 00-49-27](https://github.com/Team-Abraxas/Abraxas-Website-2024/assets/122690804/bb97ab3f-f90b-4bc8-808f-35ac44bdaa2c)

**Comment by ashmitjsg** [comment]
Completed in PR #5
