### ISSUE TITLE
feat: create 3D models for projects

### ISSUE THREAD

**Issue by ashmitjsg** [Team-Abraxas/Abraxas-Website-2024#3]
Create 3D Model (.gltf) file of 2023 & 2024 models

**Comment by mesatyammaurya** [comment]
Created 3D Model of Ionic wind Demonstration (.stl file)

**Comment by ashmitjsg** [comment]
@mesatyammaurya What's the timeline you have decided?

**Comment by mesatyammaurya** [comment]
22nd March for the  models of all  previous year projects.

**Comment by ashmitjsg** [comment]
Completed in #5
